language: node_js
sudo: false
env:
   - TEST_SUITE=test-lib
   - TEST_SUITE=test-additional
   - TEST_SUITE=test-legacy-tasks
   - TEST_SUITE=test-flow-tasks
node_js:
   - "0.12"
   - "0.10"
script: "grunt $TEST_SUITE"
notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template:
         - "%{repository_slug} (%{commit}) [%{branch}]: %{message}"
      use_notice: true
branches:
   except:
      - /^feature\/.*$/

